project:
  type: website
  render:
    - "*.qmd"
    - "!webexercises.qmd"
    - "!Untitled.qmd"
    - "!quarto_quiz.qmd"
    - "!show_quarto_quiz_1.qmd"
    - "!about.qmd"
    - "!cours_semaine_1.qmd"
  resources:
    - content/
website:
  page-navigation: true
  title: "Introduction à la Statistique"
  description: "Site web du cours Introduction à la Statistique"
  site-url: "intro-statistique.netlify.app"
  repo-url: "https://github.com/SMAC-Group/course_introduction_statistics"
  repo-branch: main
  navbar:
    right:
    - icon: github
      href: "https://github.com/SMAC-Group/course_introduction_statistics"  
    left:
    - href: index.qmd
      text: Accueil
    - href: chatbot_slides.qmd
      text: Chatbot Slides
    - text: Exercices
      menu:
      - href: exercices_semaine_1.qmd
      - href: exercices_semaine_2.qmd
      - href: exercices_semaine_3.qmd
      - href: exercices_semaine_4.qmd
      - href: exercices_semaine_5.qmd
      - href: exercices_semaine_6.qmd
      - href: exercices_semaine_8.qmd
      - href: exercices_semaine_9.qmd
      - href: exercices_semaine_11.qmd
      - href: exercices_semaine_12.qmd
execute:
  freeze: auto
format:
  html:
    theme:
    - readable
    - brand
    css:
    - styles.css
    - include/webex.css
    - include/chat.css
    toc: true
    include-after-body:
    - include/webex.js
    - include/chat.js
    - include/site-features.js
