[build]
  publish = "_site"

[functions]
  directory = "netlify/functions"

[dev]
  publish = "_site"
  port = 8888
  autoLaunch = false
  command = "quarto preview"

# Plugin installs Quarto and runs 'quarto render'
[[plugins]]
  package = "@quarto/netlify-plugin-quarto"
  [plugins.inputs]
    version = "latest"
    cmd = "render"
